spring.application.name=DemoHotelBooking

# H2 Database Configurations
spring.datasource.url=jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console Configurations
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

# Java Mail Configurations (Mock/Console Logging by default, can be overridden)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chalasanilokesh@gmail.com
spring.mail.password=plooogphaathgaln
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true

# Custom JWT Configuration
hotel.app.jwtSecret=DemoHotelBookingSecretKeyMustBeLongEnoughForHS512SignatureAndVerificationDemoHotelBookingSecretKeyMustBeLongEnoughForHS512SignatureAndVerification
hotel.app.jwtExpirationMs=86400000

# Swagger UI Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha

# Enable frames for H2 Console
spring.headers.frame-options=sameorigin
